import { PlayerAction } from "./actions/Action";
import { GamePhase, TurnStep } from "./models/enums";
import { GameState } from "./models/GameState";
// import { v4 as uuidv4 } from 'uuid'; // we would use this for IDs

export class GameEngine {
  private state: GameState;

  constructor(initialState: GameState) {
    this.state = initialState;
  }

  public getState(): GameState {
    return this.state;
  }

  /**
   * Main entry point for player actions.
   * Returns a list of events generated by this action (for animations, logs, etc.)
   */
  public dispatch(action: PlayerAction): any[] {
    const events: any[] = [];

    // 1. Verify it is the player's turn (unless it's a response action)
    if (
      this.state.activePlayerId !== action.playerId &&
      this.state.gamePhase !== GamePhase.Setup
    ) {
      throw new Error("Not your turn");
    }

    // 2. Route the action
    switch (action.type) {
      case "END_TURN":
        this.endTurn(events);
        break;
      // TODO: implement other actions
      default:
        throw new Error(`Action ${action.type} not implemented`);
    }

    return events;
  }

  private endTurn(events: any[]) {
    // 1. Pokémon Checkup (Poison, Burn, Sleep, Paralysis)
    this.pokemonCheckup(events);

    // 2. Switch active player
    const nextPlayerId = this.state.playerIds.find(
      (id) => id !== this.state.activePlayerId,
    )!;
    this.state.activePlayerId = nextPlayerId;
    this.state.turnNumber++;
    this.state.turnStep = TurnStep.Draw;

    // Reset turn flags
    this.state.players[nextPlayerId].hasAttachedEnergyThisTurn = false;
    this.state.players[nextPlayerId].hasPlayedSupporterThisTurn = false;
    this.state.players[nextPlayerId].hasRetreatedThisTurn = false;

    events.push({ type: "TURN_ENDED", newActivePlayer: nextPlayerId });

    // 3. Draw phase
    this.drawCard(nextPlayerId, events);
    this.state.turnStep = TurnStep.Main;
  }

  private pokemonCheckup(events: any[]) {
    // Implement special condition logic (damage from poison/burn, coin flips for sleep/burn)
    // Clear paralysis at the end of the checkup for the player whose turn just ended? No, paralysis goes away at the end of the paralyzed player's turn.
  }

  private drawCard(playerId: string, events: any[]) {
    const player = this.state.players[playerId];
    if (player.deck.length === 0) {
      this.state.gamePhase = GamePhase.Finished;
      this.state.winnerId = this.state.playerIds.find((id) => id !== playerId)!;
      events.push({
        type: "GAME_OVER",
        reason: "DECK_OUT",
        winnerId: this.state.winnerId,
      });
      return;
    }
    const card = player.deck.pop()!;
    player.hand.push(card);
    events.push({ type: "CARD_DRAWN", playerId, count: 1 }); // Don't expose card instance to the other player in this event usually
  }
}
