import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Aligns sealed products on the model already used by cards and sets.
 *
 * `sealed_product_locale` gets a composite primary key, replacing a generated
 * id that carried no meaning and forced name resolution through a query
 * builder. It also gets the trigram index the search relies on.
 *
 * `sealed_product.nameEn` goes away: despite its name it held the French label
 * scraped from Pokécardex, so every reader of that column was reading French
 * while believing it was English. Its content is moved to the `fr` translation
 * before the column is dropped.
 *
 * Destructive migration: `down` recreates the column and refills it from the
 * default locale.
 */
export class SealedProductTranslations1786078800000
  implements MigrationInterface
{
  name = "SealedProductTranslations1786078800000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    // The table predates the migration history: it was created by TypeORM's
    // synchronize, so it may or may not already exist.
    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS "sealed_product_locale" (
        "sealed_product_id" character varying NOT NULL,
        "locale" character varying(10) NOT NULL,
        "name" character varying NOT NULL,
        "createdAt" TIMESTAMP NOT NULL DEFAULT now()
      )
    `);

    // Preserve the scraped label before the column disappears.
    await queryRunner.query(`
      INSERT INTO "sealed_product_locale" ("sealed_product_id", "locale", "name")
      SELECT p."id", 'fr', p."nameEn"
      FROM "sealed_product" p
      WHERE p."nameEn" IS NOT NULL
        AND NOT EXISTS (
          SELECT 1 FROM "sealed_product_locale" l
          WHERE l."sealed_product_id" = p."id" AND l."locale" = 'fr'
        )
    `);

    // A duplicate would block the composite key. Keeps the row inserted last.
    await queryRunner.query(`
      DELETE FROM "sealed_product_locale" l
      USING "sealed_product_locale" other
      WHERE l."sealed_product_id" = other."sealed_product_id"
        AND l."locale" = other."locale"
        AND l.ctid < other.ctid
    `);

    // Constraint names were generated by synchronize, so they are looked up
    // rather than assumed. Foreign keys are included: leaving the generated one
    // in place next to the one added below would duplicate it.
    await queryRunner.query(`
      DO $$
      DECLARE target text;
      BEGIN
        FOR target IN
          SELECT conname FROM pg_constraint
          WHERE conrelid = 'sealed_product_locale'::regclass
            AND contype IN ('p', 'u', 'f')
        LOOP
          EXECUTE format(
            'ALTER TABLE "sealed_product_locale" DROP CONSTRAINT %I', target
          );
        END LOOP;
      END $$
    `);

    await queryRunner.query(`
      ALTER TABLE "sealed_product_locale" DROP COLUMN IF EXISTS "id"
    `);
    // `locale` is narrowed to varchar(10), as on `card_translation`: an older
    // table created by synchronize has it unbounded, which the entity no longer
    // matches — synchronize would then try to rewrite the primary key column.
    await queryRunner.query(`
      ALTER TABLE "sealed_product_locale"
        ALTER COLUMN "sealed_product_id" SET NOT NULL,
        ALTER COLUMN "locale" TYPE character varying(10),
        ALTER COLUMN "locale" SET NOT NULL,
        ALTER COLUMN "name" SET NOT NULL
    `);
    await queryRunner.query(`
      ALTER TABLE "sealed_product_locale"
        ADD CONSTRAINT "PK_sealed_product_locale"
        PRIMARY KEY ("sealed_product_id", "locale")
    `);

    await queryRunner.query(`
      ALTER TABLE "sealed_product_locale"
        DROP CONSTRAINT IF EXISTS "FK_sealed_product_locale_product"
    `);
    await queryRunner.query(`
      ALTER TABLE "sealed_product_locale"
        ADD CONSTRAINT "FK_sealed_product_locale_product"
        FOREIGN KEY ("sealed_product_id")
        REFERENCES "sealed_product" ("id") ON DELETE CASCADE
    `);

    // Marketplace search runs an ILIKE '%…%' on an accent-folded expression:
    // only a trigram index can serve it, and the expression must be written
    // exactly as in `sealedProductNameMatchesSql`.
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_sealed_product_locale_name_trgm"
      ON "sealed_product_locale"
      USING gin (immutable_unaccent("name") gin_trgm_ops)
    `);
    await queryRunner.query(`
      CREATE INDEX IF NOT EXISTS "IDX_sealed_product_locale_locale_name"
      ON "sealed_product_locale" ("locale", "name")
    `);

    await queryRunner.query(`
      ALTER TABLE "sealed_product" DROP COLUMN IF EXISTS "nameEn"
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "sealed_product" ADD COLUMN "nameEn" character varying
    `);
    await queryRunner.query(`
      UPDATE "sealed_product" p SET "nameEn" = l."name"
      FROM "sealed_product_locale" l
      WHERE l."sealed_product_id" = p."id" AND l."locale" = 'fr'
    `);

    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_sealed_product_locale_locale_name"`,
    );
    await queryRunner.query(
      `DROP INDEX IF EXISTS "IDX_sealed_product_locale_name_trgm"`,
    );

    await queryRunner.query(`
      ALTER TABLE "sealed_product_locale"
        DROP CONSTRAINT IF EXISTS "PK_sealed_product_locale"
    `);
    await queryRunner.query(`
      ALTER TABLE "sealed_product_locale" ADD COLUMN "id" SERIAL PRIMARY KEY
    `);
    await queryRunner.query(`
      ALTER TABLE "sealed_product_locale"
        ADD CONSTRAINT "UQ_sealed_product_locale_product_locale"
        UNIQUE ("sealed_product_id", "locale")
    `);
  }
}
