export const SCANNER_CONFIG = {
  CARD_ASPECT_RATIO: 63 / 88, // ≈ 0.716

  CARD_RATIO_TOLERANCE: 0.1,

  NORMALIZED_WIDTH: 420,
  NORMALIZED_HEIGHT: 588,

  NAME_ZONE: { top: 0, bottom: 0.15 }, // Nom : 0–15%
  NUMBER_ZONE: { top: 0.82, bottom: 1.0 },

  CONFIDENCE_HIGH_THRESHOLD: 80,
  CONFIDENCE_MEDIUM_THRESHOLD: 45,

  SCORE_NAME_EXACT: 40,
  SCORE_NAME_PARTIAL: 20,
  SCORE_NUMBER_EXACT: 40,
  SCORE_NUMBER_PARTIAL: 20,
  SCORE_SET_COHERENT: 15,
  SCORE_VISUAL: 30, // Phase 2

  OCR_CROP_QUALITY: 0.92,

  OCR_RESIZE_WIDTH: 1200,
} as const;
