export enum PokemonCardsType {
  Pokemon = "Pokemon",
  Energy = "Energy",
  Trainer = "Trainer",
}

export enum PokemonRarity {
  CHROMATIQUE_ULTRA_RARE = "chromatique ultra rare",
  ULTRA_RARE = "Ultra Rare",
  SHINY_RARE_VMAX = "Shiny rare VMAX",
  SHINY_RARE_V = "Shiny rare V",
  SHINY_RARE = "Shiny rare",
  SANS_RARETE = "Sans Rareté",
  RARE_PRIME = "Rare Prime",
  RARE_HOLO_LV_X = "Rare Holo LV.X",
  RARE_HOLO = "Rare Holo",
  RARE = "Rare",
  RADIEUX_RARE = "Radieux Rare",
  PEU_COMMUNE = "Peu Commune",
  MAGNIFIQUE_RARE = "Magnifique rare",
  MAGNIFIQUE = "Magnifique",
  LEGENDE = "LÉGENDE",
  ILLUSTRATION_SPECIALE_RARE = "Illustration spéciale rare",
  ILLUSTRATION_RARE = "Illustration rare",
  HYPER_RARE = "Hyper rare",
  HOLO_RARE_VSTAR = "Holo Rare VSTAR",
  HOLO_RARE_VMAX = "Holo Rare VMAX",
  HOLO_RARE_V = "Holo Rare V",
  HOLO_RARE = "Holo Rare",
  HIGH_TECG_RARE = "HIGH-TECG rare",
  DRESSEUR_FULL_ART = "Dresseur Full Art",
  DOUBLE_RARE = "Double rare",
  COMMUNE = "Commune",
}
