import { ApiProperty } from "@nestjs/swagger";
import { IsNotEmpty, IsString } from "class-validator";

/**
 * Payload for mobile OAuth PKCE authorization code exchange.
 */
export class MobileOAuthExchangeDto {
  @ApiProperty({
    description: "Authorization code received from OAuth provider",
    example: "4/0AWgavdfjkls...",
  })
  @IsString()
  @IsNotEmpty()
  code: string;

  @ApiProperty({
    description: "PKCE code verifier matching the challenge generated by mobile app",
    example: "dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk",
  })
  @IsString()
  @IsNotEmpty()
  codeVerifier: string;

  @ApiProperty({
    description: "Mobile redirect URI configured in OAuth provider console",
    example: "tcgnexus://auth/callback",
  })
  @IsString()
  @IsNotEmpty()
  redirectUri: string;
}
