name: Mirror to GitLab

# se déclenche à chaque push de branche ou de tag
on:
  push:
    branches:
      - '**'
    tags:
      - '*'

# empêche deux runs simultanés
concurrency:
  group: mirror-to-gitlab
  cancel-in-progress: true

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      # 1) récupérer tout l'historique
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) configurer l'identité Git pour le push
      - name: Set Git user
        run: |
          git config user.name  "Mirror Bot"
          git config user.email "mirror-bot@example.com"

      # 3) ajouter le remote GitLab via le token
      - name: Add GitLab remote
        run: |
          git remote add gitlab \
            https://oauth2:${{ secrets.GITLAB_TOKEN }}@rendu-git.etna-alternance.net/module-10020/activity-53631/group-1056981.git

      # 4) pousser toutes les branches
      - name: Push all branches to GitLab
        run: git push --prune --all gitlab

      # 5) pousser tous les tags
      - name: Push all tags to GitLab
        run: git push --tags gitlab